Repository atlanhq/atlas-metastore, pull requests merged in 2021-12, with the labels that each got.

#174 META-2736 - Policy Evaluator - added entity lookup for entityGuid case.
  intg/src/main/java/org/apache/atlas/model/instance/AtlasEvaluatePolicyResponse.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/AtlasEntityStore.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: READY FOR REVIEW

#218 Lineage API: add __hasLineage attr for indexsearch filtering
  common/src/main/java/org/apache/atlas/repository/Constants.java
  intg/src/main/java/org/apache/atlas/type/Constants.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphBackedSearchIndexer.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityMutationContext.java
Labels: READY FOR REVIEW

#230 META-2766 GCT entities createOrUpdate with entity REST bugs
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/glossary/CategoryPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/glossary/GlossaryUtils.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/glossary/TermPreProcessor.java
Labels: READY FOR REVIEW

#237 META-2777 ClassCastException: When adding meanings to entity
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
Labels: READY FOR REVIEW

#233 Meta 2774 PreProcessors for Query, QueryFolder, QueryCollection & Connection
  common/src/main/java/org/apache/atlas/repository/Constants.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/glossary/GlossaryUtils.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/glossary/PreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/PreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/PreProcessorUtils.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/CategoryPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/GlossaryPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/TermPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/sql/QueryCollectionPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/sql/QueryFolderPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/sql/QueryPreProcessor.java
Labels: DO NOT MERGE

#228 META-2768 __hasLineage is not added for Columns
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
Labels: READY FOR REVIEW

#221 META-2763: Soft DELETE of edges does not remove propagated tags
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/SoftDeleteHandlerV1.java
Labels: READY FOR REVIEW

#223 META-2765: Prevent relationship create if both ends are referring to same vertex
  graphdb/api/src/main/java/org/apache/atlas/repository/graphdb/AtlasGraph.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusGraph.java
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasTypeDefGraphStoreV2.java
Labels: READY FOR REVIEW

#238 META-2772 TypeDefs GET: type query param should support multiple values
  repository/src/main/java/org/apache/atlas/repository/util/FilterUtil.java
  webapp/src/main/java/org/apache/atlas/web/rest/TypesREST.java
Labels: READY FOR REVIEW

#253 META-2784 Performance Improvement: Glossary, Term creation
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasGraphUtilsV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/glossary/CategoryPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/glossary/GlossaryPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/glossary/TermPreProcessor.java
Labels: READY FOR REVIEW

#254 META-2770 Deleting a category must remove __parentCategory attribute…
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
Labels: READY FOR REVIEW

#256 META-2774 PreProcessors for Query, QueryFolder, QueryCollection
  common/src/main/java/org/apache/atlas/repository/Constants.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/glossary/GlossaryUtils.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/glossary/PreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/PreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/PreProcessorUtils.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/CategoryPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/GlossaryPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/TermPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/sql/QueryCollectionPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/sql/QueryFolderPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/sql/QueryPreProcessor.java
Labels: READY FOR REVIEW

#263 META-2788 indexsearch: add input param to disable sending deleted rel…
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/model/discovery/IndexSearchParams.java
  repository/src/main/java/org/apache/atlas/discovery/EntityDiscoveryService.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
Labels: READY FOR REVIEW

#243 fix: entity audits missing in Cassandra
  repository/src/main/java/org/apache/atlas/repository/audit/CassandraBasedAuditRepository.java
Labels: READY FOR REVIEW

#246 added: ability to toggle search score in indexsearch
  intg/src/main/java/org/apache/atlas/model/discovery/SearchParams.java
  repository/src/main/java/org/apache/atlas/discovery/EntityDiscoveryService.java
Labels: READY FOR REVIEW

#258 META-2760 Authz check for Atlas setClassifications endpoint
  repository/src/main/java/org/apache/atlas/repository/store/graph/AtlasEntityStore.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/ClassificationAssociator.java
  repository/src/test/java/org/apache/atlas/repository/store/graph/v2/ClassificationAssociatorTest.java
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: READY FOR REVIEW

#265 META-2796 Bulk delete entities endpoint on unique attributes
  repository/src/main/java/org/apache/atlas/repository/store/graph/AtlasEntityStore.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: READY FOR REVIEW

#268 META-2797 TypeDef: do not set name into displayName if dispalyName is…
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasTypeDefGraphStoreV2.java
Labels: READY FOR REVIEW

#273 META-2798 BM: Enable multivalued for Enum type attributes
  intg/src/main/java/org/apache/atlas/type/AtlasBusinessMetadataType.java
  intg/src/main/java/org/apache/atlas/type/AtlasStructType.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphBackedSearchIndexer.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
Labels: READY FOR REVIEW

#276 META-2800 BM: deleting BM typeDef fails even if not assigned to entity
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasBusinessMetadataDefStoreV2.java
Labels: READY FOR REVIEW

#282 Upgrade log4j to 2.17.0
  pom.xml
Labels: READY FOR REVIEW

#306 ATLAS-4431: Random NPE when retrieving tasks (part2 - additional null…
  repository/src/main/java/org/apache/atlas/tasks/TaskRegistry.java
Labels: READY FOR REVIEW

#303 upgrade es to 7.16.2
  pom.xml
  webapp/src/main/java/org/apache/atlas/Atlas.java
Labels: DO NOT MERGE, master

#304 META-2814 ES Audits: entityQualifiedName is null for some records
  repository/src/main/java/org/apache/atlas/repository/audit/ESBasedAuditRepository.java
  repository/src/main/java/org/apache/atlas/repository/audit/EntityAuditListenerV2.java
Labels: READY FOR REVIEW

#311 META-2804 META-2818 Lineage API enhancements
  intg/src/main/java/org/apache/atlas/model/lineage/AtlasLineageContext.java
  intg/src/main/java/org/apache/atlas/model/lineage/AtlasLineageInfo.java
  intg/src/main/java/org/apache/atlas/model/lineage/AtlasLineageRequest.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasLineageService.java
  repository/src/main/java/org/apache/atlas/discovery/EntityLineageService.java
  webapp/src/main/java/org/apache/atlas/web/rest/LineageREST.java
Labels: READY FOR REVIEW

#316 Meta 2819
  addons/elasticsearch/es-audit-mappings.json
  intg/src/main/java/org/apache/atlas/model/audit/EntityAuditEventV2.java
  repository/src/main/java/org/apache/atlas/repository/audit/ESBasedAuditRepository.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
Labels: READY FOR REVIEW

#317 META-2820 Delete entity fails due to stale propagated classification
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: READY FOR REVIEW
