Repository atlanhq/atlas-metastore, pull requests merged in 2023-05, with the labels that each got.

#1865 Feat/lineage list api
  intg/src/main/java/org/apache/atlas/model/lineage/AtlasLineageListInfo.java
  intg/src/main/java/org/apache/atlas/model/lineage/LineageListRequest.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasLineageListContext.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasLineageService.java
  repository/src/main/java/org/apache/atlas/discovery/EntityLineageService.java
  webapp/src/main/java/org/apache/atlas/web/rest/LineageREST.java
Labels: DO NOT MERGE

#1721 Feat/lin 329 list api
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  intg/src/main/java/org/apache/atlas/model/lineage/AtlasLineageListInfo.java
  intg/src/main/java/org/apache/atlas/model/lineage/AtlasLineageSizeInfo.java
  intg/src/main/java/org/apache/atlas/model/lineage/LineageListRequest.java
  intg/src/main/java/org/apache/atlas/model/lineage/LineageSizeRequest.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasLineageListContext.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasLineageService.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasLineageSizeContext.java
  repository/src/main/java/org/apache/atlas/discovery/EntityLineageService.java
  webapp/src/main/java/org/apache/atlas/web/rest/LineageREST.java
Labels: READY FOR REVIEW

#1785 Feat/lin 329 list api
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  intg/src/main/java/org/apache/atlas/model/lineage/AtlasLineageListInfo.java
  intg/src/main/java/org/apache/atlas/model/lineage/AtlasLineageSizeInfo.java
  intg/src/main/java/org/apache/atlas/model/lineage/LineageListRequest.java
  intg/src/main/java/org/apache/atlas/model/lineage/LineageSizeRequest.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasLineageListContext.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasLineageService.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasLineageSizeContext.java
  repository/src/main/java/org/apache/atlas/discovery/EntityLineageService.java
  webapp/src/main/java/org/apache/atlas/web/rest/LineageREST.java
Labels: DO NOT MERGE

#1951 PLT-637 Search logs
  addons/elasticsearch/es-search-logs-mappings.json
  authorization/src/main/java/org/apache/atlas/authorize/simple/AtlasSimpleAuthorizer.java
  common/src/main/java/org/apache/atlas/repository/Constants.java
  graphdb/api/src/main/java/org/apache/atlas/repository/graphdb/AtlasIndexQuery.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchQuery.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusIndexQuery.java
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/model/discovery/IndexSearchParams.java
  intg/src/main/java/org/apache/atlas/model/discovery/SearchParams.java
  intg/src/main/java/org/apache/atlas/model/searchlog/SearchLogSearchParams.java
  intg/src/main/java/org/apache/atlas/model/searchlog/SearchLogSearchResult.java
  intg/src/main/java/org/apache/atlas/model/searchlog/SearchRequestLogData.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasDiscoveryService.java
  repository/src/main/java/org/apache/atlas/discovery/EntityDiscoveryService.java
  repository/src/main/java/org/apache/atlas/searchlog/ESSearchLogger.java
  repository/src/main/java/org/apache/atlas/searchlog/SearchLogger.java
  repository/src/main/java/org/apache/atlas/searchlog/SearchLoggingConsumer.java
  repository/src/main/java/org/apache/atlas/searchlog/SearchLoggingManagement.java
  webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java
Labels: DO NOT MERGE, READY FOR REVIEW

#1972 Search logs may master
  addons/elasticsearch/es-search-logs-mappings.json
  common/src/main/java/org/apache/atlas/repository/Constants.java
  graphdb/api/src/main/java/org/apache/atlas/repository/graphdb/AtlasIndexQuery.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchQuery.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusIndexQuery.java
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/model/discovery/IndexSearchParams.java
  intg/src/main/java/org/apache/atlas/model/discovery/SearchParams.java
  intg/src/main/java/org/apache/atlas/model/searchlog/SearchLogSearchParams.java
  intg/src/main/java/org/apache/atlas/model/searchlog/SearchLogSearchResult.java
  intg/src/main/java/org/apache/atlas/model/searchlog/SearchRequestLogData.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasDiscoveryService.java
  repository/src/main/java/org/apache/atlas/discovery/EntityDiscoveryService.java
  repository/src/main/java/org/apache/atlas/searchlog/ESSearchLogger.java
  repository/src/main/java/org/apache/atlas/searchlog/SearchLogger.java
  repository/src/main/java/org/apache/atlas/searchlog/SearchLoggingConsumer.java
  repository/src/main/java/org/apache/atlas/searchlog/SearchLoggingManagement.java
  webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java
Labels: READY FOR REVIEW

#1993 Plt 769 policy refresh issue, conditional load authz typeDefs
  intg/src/main/java/org/apache/atlas/featureflag/FeatureFlagStore.java
  repository/src/main/java/org/apache/atlas/repository/store/bootstrap/AtlasTypeDefStoreInitializer.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/util/AccessControlUtils.java
  webapp/src/main/java/org/apache/atlas/web/rest/AuthREST.java
Labels: READY FOR REVIEW
