Repository atlanhq/atlas-metastore, pull requests merged in 2024-10, with the labels that each got.

#3576 CJ-165 | Add support for bulk in data models
  common/src/main/java/org/apache/atlas/repository/Constants.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityGraphDiscoveryV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasGraphUtilsV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityMutationContext.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/IDBasedEntityResolver.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/model/AbstractModelPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/model/DMAttributeAssociationPreprocessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/model/DMAttributePreprocessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/model/DMEntityAssociationPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/model/DMEntityPreProcessor.java
  webapp/src/main/java/org/apache/atlas/web/rest/ModelREST.java
Labels: beta

#3590 DG-1831 Add Metric log to calculate hasEdges impact
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusGraph.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusVertex.java
Labels: READY FOR REVIEW

#3602 CJ- 165 | Fix constants name in Consumption API
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  webapp/src/main/java/org/apache/atlas/web/util/ModelUtil.java
Labels: bug, beta, READY FOR REVIEW

#3609 DG-1791 | Retrieve only the active edges
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/DeleteHandlerV1.java
Labels: READY FOR REVIEW

#3608 DG-1791 | Retrieve only the active edges
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/DeleteHandlerV1.java
Labels: READY FOR REVIEW

#3265 DG-1442 Modification of the PreProcessor for Custom Sort - Bulk Update Edge Cases
  intg/src/main/java/org/apache/atlas/type/Constants.java
  repository/src/main/java/org/apache/atlas/glossary/GlossaryUtils.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/PreProcessorUtils.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/CategoryPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/GlossaryPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/TermPreProcessor.java
  repository/src/main/java/org/apache/atlas/util/lexoRank/LexoDecimal.java
  repository/src/main/java/org/apache/atlas/util/lexoRank/LexoInteger.java
  repository/src/main/java/org/apache/atlas/util/lexoRank/LexoRank.java
  repository/src/main/java/org/apache/atlas/util/lexoRank/LexoRankBucket.java
  repository/src/main/java/org/apache/atlas/util/lexoRank/system/LexoNumeralSystem.java
  repository/src/main/java/org/apache/atlas/util/lexoRank/system/LexoNumeralSystem36.java
  repository/src/main/java/org/apache/atlas/util/lexoRank/system/LexoNumeralSystem64.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
Labels: DO NOT MERGE

#3632 DG-1746 Fix edge not getting removed issue
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/DeleteHandlerV1.java
Labels: READY FOR REVIEW

#3383 DQ-165 Prevent user YAML override
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/contract/ContractPreProcessor.java
Labels: READY FOR REVIEW

#3644 DG-1791 | Cache computation logic for vertex label combination
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/DeleteHandlerV1.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
Labels: READY FOR REVIEW
