Repository atlanhq/atlas-metastore, pull requests merged in 2024-01, with the labels that each got.

#2732 Update Classification add/delete behaviour
  intg/src/main/java/org/apache/atlas/model/audit/EntityAuditEventV2.java
  intg/src/main/java/org/apache/atlas/type/AtlasTypeRegistry.java
  repository/src/main/java/org/apache/atlas/repository/audit/ESBasedAuditRepository.java
  repository/src/main/java/org/apache/atlas/repository/audit/EntityAuditListenerV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/ClassificationAssociator.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
Labels: enhancement, beta

#2736 feat: Policy Cache mechanism improvements[staging]
  auth-agents-common/pom.xml
  auth-agents-common/src/main/java/org/apache/atlas/plugin/util/KeycloakUserStore.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/util/RangerUserStoreProvider.java
  client-auth/pom.xml
  client-auth/src/main/java/org/apache/atlas/auth/client/auth/AbstractAuthClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/auth/KeycloakAuthenticationService.java
  client-auth/src/main/java/org/apache/atlas/auth/client/config/AuthConfig.java
  client-auth/src/main/java/org/apache/atlas/auth/client/config/AuthConfigBuilder.java
  client-auth/src/main/java/org/apache/atlas/auth/client/heracles/AtlasHeraclesClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/heracles/HeraclesRestClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/heracles/RetrofitHeraclesClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/heracles/models/HeraclesRoleViewRepresentation.java
  client-auth/src/main/java/org/apache/atlas/auth/client/heracles/models/HeraclesUserViewRepresentation.java
  client-auth/src/main/java/org/apache/atlas/auth/client/keycloak/AtlasKeycloakClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/keycloak/KeycloakRestClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/keycloak/RetrofitKeycloakClient.java
  client-heracles/pom.xml
  client-heracles/src/main/java/heracles/client/config/HeraclesConfigBuilder.java
  client-keycloak/src/main/java/org/apache/atlas/keycloak/client/config/KeycloakConfigBuilder.java
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  pom.xml
  repository/pom.xml
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/ConnectionPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/accesscontrol/PersonaPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/sql/QueryCollectionPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/users/KeycloakStore.java
  webapp/src/main/java/org/apache/atlas/web/rest/MigrationREST.java
  webapp/src/main/java/org/apache/atlas/web/security/AtlasKeycloakAuthenticationProvider.java
Labels: READY FOR REVIEW

#2751 feat: Policy Cache mechanism improvements
  auth-agents-common/pom.xml
  auth-agents-common/src/main/java/org/apache/atlas/plugin/util/KeycloakUserStore.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/util/RangerUserStoreProvider.java
  client-auth/pom.xml
  client-auth/src/main/java/org/apache/atlas/auth/client/auth/AbstractAuthClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/auth/KeycloakAuthenticationService.java
  client-auth/src/main/java/org/apache/atlas/auth/client/config/AuthConfig.java
  client-auth/src/main/java/org/apache/atlas/auth/client/config/AuthConfigBuilder.java
  client-auth/src/main/java/org/apache/atlas/auth/client/heracles/AtlasHeraclesClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/heracles/HeraclesRestClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/heracles/RetrofitHeraclesClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/heracles/models/HeraclesRoleViewRepresentation.java
  client-auth/src/main/java/org/apache/atlas/auth/client/heracles/models/HeraclesUserViewRepresentation.java
  client-auth/src/main/java/org/apache/atlas/auth/client/keycloak/AtlasKeycloakClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/keycloak/KeycloakRestClient.java
  client-auth/src/main/java/org/apache/atlas/auth/client/keycloak/RetrofitKeycloakClient.java
  client-heracles/pom.xml
  client-heracles/src/main/java/heracles/client/config/HeraclesConfigBuilder.java
  client-keycloak/src/main/java/org/apache/atlas/keycloak/client/config/KeycloakConfigBuilder.java
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  pom.xml
  repository/pom.xml
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/ConnectionPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/accesscontrol/PersonaPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/sql/QueryCollectionPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/users/KeycloakStore.java
  webapp/src/main/java/org/apache/atlas/web/rest/MigrationREST.java
  webapp/src/main/java/org/apache/atlas/web/security/AtlasKeycloakAuthenticationProvider.java
Labels: READY FOR REVIEW

#2744 PLT-573 | Add removeSupport in bulk API
  intg/src/main/java/org/apache/atlas/model/instance/AtlasEntity.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/AtlasRelationshipStore.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/EntityGraphDiscoveryContext.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityGraphDiscoveryV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasRelationshipStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityMutationContext.java
Labels: DO NOT MERGE, READY FOR REVIEW, master

#2784 Beta | Optimise append operation and enhance error messages
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityGraphDiscoveryV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
Labels: beta

#2778 Optimise append operation and enhance error messages
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityGraphDiscoveryV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AttributeMutationContext.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
Labels: DO NOT MERGE, READY FOR REVIEW, master

#2792 [beta] Newauthz beta helper
  auth-agents-common/pom.xml
  auth-agents-common/src/main/java/org/apache/atlas/plugin/model/RangerBaseModelObject.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/model/RangerPolicy.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/service/RangerBasePlugin.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/util/ServicePolicies.java
  auth-agents-common/src/main/java/org/apache/atlas/policytransformer/CachePolicyTransformerImpl.java
  auth-agents-common/src/main/java/org/apache/atlas/policytransformer/PersonaCachePolicyTransformer.java
  auth-common/pom.xml
  auth-common/src/main/java/org/apache/atlas/plugin/model/GroupInfo.java
  auth-common/src/main/java/org/apache/atlas/plugin/model/NewAccessResourceImpl.java
  auth-common/src/main/java/org/apache/atlas/plugin/model/RangerBaseModelObject.java
  auth-common/src/main/java/org/apache/atlas/plugin/model/RangerPolicy.java
  auth-common/src/main/java/org/apache/atlas/plugin/model/RangerRole.java
  auth-common/src/main/java/org/apache/atlas/plugin/model/RangerServiceDef.java
  auth-common/src/main/java/org/apache/atlas/plugin/model/RangerValidityRecurrence.java
  auth-common/src/main/java/org/apache/atlas/plugin/model/RangerValiditySchedule.java
  auth-common/src/main/java/org/apache/atlas/plugin/model/UserInfo.java
  auth-common/src/main/java/org/apache/atlas/plugin/util/RangerRoles.java
  auth-common/src/main/java/org/apache/atlas/plugin/util/RangerUserStore.java
  auth-common/src/main/java/org/apache/atlas/plugin/util/RangerUserStoreUtil.java
  authorization/src/main/java/org/apache/atlas/authorize/AtlasAuthorizationUtils.java
  intg/src/main/java/org/apache/atlas/model/discovery/SearchParams.java
  pom.xml
  repository/pom.xml
  repository/src/main/java/org/apache/atlas/authorizer/AccessResult.java
  repository/src/main/java/org/apache/atlas/authorizer/AccessorsExtractor.java
  repository/src/main/java/org/apache/atlas/authorizer/AuthorizerUtils.java
  repository/src/main/java/org/apache/atlas/authorizer/JsonToElasticsearchQuery.java
  repository/src/main/java/org/apache/atlas/authorizer/NewAtlasAuditHandler.java
  repository/src/main/java/org/apache/atlas/authorizer/NewAuthorizerUtils.java
  repository/src/main/java/org/apache/atlas/authorizer/authorizers/AuthorizerCommon.java
  repository/src/main/java/org/apache/atlas/authorizer/authorizers/EntityAuthorizer.java
  repository/src/main/java/org/apache/atlas/authorizer/authorizers/ListAuthorizer.java
  repository/src/main/java/org/apache/atlas/authorizer/authorizers/RelationshipAuthorizer.java
  repository/src/main/java/org/apache/atlas/authorizer/store/PoliciesStore.java
  repository/src/main/java/org/apache/atlas/authorizer/store/UsersStore.java
  repository/src/main/java/org/apache/atlas/discovery/EntityDiscoveryService.java
  repository/src/main/java/org/apache/atlas/discovery/EntityLineageService.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/AtlasEntityStore.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/DeleteHandlerV1.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasRelationshipStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/AuthPolicyPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/AbstractGlossaryPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/CategoryPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/glossary/TermPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/resource/AbstractResourcePreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/util/AccessControlUtils.java
  repository/src/main/resources/atlas-servicedef-atlas.json
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: DO NOT MERGE

#2803 fix: Add error code for unknown errors so we could run pinpoint on them
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: READY FOR REVIEW
