Repository atlanhq/atlas-metastore, pull requests merged in 2024-02, with the labels that each got.

#2824 DG-898 Fix Persona custom asset expression
  repository/src/main/java/org/apache/atlas/repository/store/aliasstore/ESAliasStore.java
Labels: DO NOT MERGE

#2828 Reduce atlas startupTime
  auth-agents-common/src/main/java/org/apache/atlas/policytransformer/CachePolicyTransformerImpl.java
  auth-audits/src/main/java/org/apache/atlas/audit/provider/AuditProviderFactory.java
  common/src/main/java/org/apache/atlas/service/Services.java
  repository/src/main/java/org/apache/atlas/GraphTransactionAdvisor.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphBackedSearchIndexer.java
  repository/src/main/java/org/apache/atlas/repository/ogm/DTORegistry.java
Labels: READY FOR REVIEW, master

#2833 feat: add indexsearch metric to app metrics
  common/src/main/java/org/apache/atlas/service/metrics/MetricsRegistry.java
  common/src/main/java/org/apache/atlas/service/metrics/MetricsRegistryServiceImpl.java
  common/src/main/java/org/apache/atlas/utils/AtlasPerfMetrics.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
  webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java
Labels: READY FOR REVIEW

#2835 Expose `displayPreferences` attribute in AccessControl
  addons/models/0000-Area0/0010-base_model.json
Labels: beta, READY FOR REVIEW

#2836 Expose `displayPreferences` attribute in AccessControl
  addons/models/0000-Area0/0010-base_model.json
Labels: master

#2840 feat: publishing histogram to get better view of indexsearch
  common/src/main/java/org/apache/atlas/service/metrics/MetricsRegistry.java
  common/src/main/java/org/apache/atlas/service/metrics/MetricsRegistryServiceImpl.java
  intg/src/main/java/org/apache/atlas/model/discovery/IndexSearchParams.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
  webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java
Labels: READY FOR REVIEW

#2844 fix: add few more buckets to generalise the histogram duration
  common/src/main/java/org/apache/atlas/service/metrics/MetricsRegistryServiceImpl.java
Labels: READY FOR REVIEW

#2869 feat: cancel ES request from metastore side if indexsearch get cancelled from the client
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchQuery.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/SearchContextCache.java
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/model/discovery/SearchParams.java
  repository/src/main/java/org/apache/atlas/discovery/EntityDiscoveryService.java
  webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java
Labels: READY FOR REVIEW
