Repository atlanhq/atlas-metastore, pull requests merged in 2024-11, with the labels that each got.

#3711 PLT-2751 : Abuse protection in Indexsearch endpoint: Put limit in indexsearch size upto 100000
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  intg/src/main/java/org/apache/atlas/model/discovery/IndexSearchParams.java
  webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java
Labels: READY FOR REVIEW

#3713 PLT-2751 : Set config to add enable the API limitting on demand
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java
Labels: READY FOR REVIEW

#3737 NOC-87266 | Configure Async behaviour for Indexsearch
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchQuery.java
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
Labels: READY FOR REVIEW, master

#3768 feat: add client origin tag in prometheus
  common/src/main/java/org/apache/atlas/service/metrics/MetricsRegistry.java
  common/src/main/java/org/apache/atlas/service/metrics/MetricsRegistryServiceImpl.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
  webapp/src/main/java/org/apache/atlas/web/filters/AuditFilter.java
Labels: READY FOR REVIEW

#3773 DG-1924 : added params for phase1 tag propogation scaling
  common/src/main/java/org/apache/atlas/repository/Constants.java
  intg/src/main/java/org/apache/atlas/model/tasks/AtlasTask.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphBackedSearchIndexer.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/tasks/TaskRegistry.java
Labels: DO NOT MERGE

#3736 DG-1907 Validate Channel Link
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/accesscontrol/AccessControlPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/accesscontrol/PersonaPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/accesscontrol/PurposePreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/util/AccessControlUtils.java
Labels: READY FOR REVIEW
