Repository atlanhq/atlas-metastore, pull requests merged in 2024-12, with the labels that each got.

#3805 FT-800 Added better message logging for unhandled exceptions
  webapp/src/main/java/org/apache/atlas/web/errors/ExceptionMapperUtil.java
Labels: READY FOR REVIEW

#3853 Janus0.6
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: beta

#3852 PLT-2782 | Janus0.6
  .github/workflows/maven.yml
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
  repository/src/main/java/org/apache/atlas/repository/util/AccessControlUtils.java
Labels: master

#3876 Janusupgrade to 1.0.0 with a smart marker logic to reduce Cassandra Calls
  build.sh
  graphdb/api/src/main/java/org/apache/atlas/repository/graphdb/AtlasGraph.java
  graphdb/janus/pom.xml
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusGraph.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusGraphDatabase.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusIndexQuery.java
  graphdb/janus/src/main/java/org/janusgraph/diskstorage/solr/Solr6Index.java
  pom.xml
  repository/pom.xml
  repository/src/main/java/org/apache/atlas/discovery/EntityDiscoveryService.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/graph/IndexRecoveryService.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
  repository/src/main/java/org/apache/atlas/services/MetricsService.java
  repository/src/main/java/org/apache/atlas/util/AtlasMetricsUtil.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
  webapp/pom.xml
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
  webapp/src/main/java/org/apache/atlas/web/service/AtlasDebugMetricsSink.java
Labels: beta

#3828 DG-1709 | Change policy refresh mechanism to only pull delta instead of all policies
  auth-agents-common/src/main/java/org/apache/atlas/authz/admin/client/AtlasAuthAdminClient.java
  auth-agents-common/src/main/java/org/apache/atlas/authz/admin/client/AtlasAuthRESTClient.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/model/RangerPolicy.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/model/RangerPolicyDelta.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/policyengine/RangerPolicyRepository.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/service/RangerBasePlugin.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/util/PolicyRefresher.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/util/RangerPolicyDeltaUtil.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/util/ServicePolicies.java
  auth-agents-common/src/main/java/org/apache/atlas/policytransformer/CachePolicyTransformerImpl.java
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/AuthPolicyPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/accesscontrol/PersonaPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/accesscontrol/PurposePreProcessor.java
  webapp/src/main/java/org/apache/atlas/web/rest/AuthREST.java
Labels: READY FOR REVIEW

#3887 Janus optimisation
  .github/workflows/maven.yml
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: beta

#3896 Cassandra : Marker logic
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: beta

#3894 Cassandra Marker logic
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: staging

#3895 PLT-2821 | Makerlogic
  .github/workflows/maven.yml
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: master

#3898 Hotfix assandra optimisation
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
  webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: beta

#3899 Hotfix cassandra optimisation
  intg/src/main/java/org/apache/atlas/model/instance/AtlasEntityHeader.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/ClassificationAssociator.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
  webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: staging

#3901 Makerlogic
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: beta

#3902 Makerlogic
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: staging

#3906 remove fallback for plocies
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: beta

#3907 remove fallback for plocies
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: staging

#3917 Cassndrahotfix
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: staging

#3916 Dev/cassndrahotfix
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: beta

#3913 PLT-2821 | Cassndrahotfix
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: master
