Repository atlanhq/atlas-metastore, pull requests merged in 2025-01, with the labels that each got.

#3897 DG-1924 | Update task vertex w impacted-vertices counts for remaining types of propagation
  .github/workflows/maven.yml
  intg/src/main/java/org/apache/atlas/model/tasks/AtlasTask.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/DeleteHandlerV1.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/tasks/TaskFactory.java
Labels: DO NOT MERGE

#3878 DG1924: Param changes in task vertex for add tags propagation to increase observability.
  .github/workflows/maven.yml
  common/src/main/java/org/apache/atlas/repository/Constants.java
  intg/src/main/java/org/apache/atlas/model/patches/AtlasPatch.java
  intg/src/main/java/org/apache/atlas/model/tasks/AtlasTask.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphBackedSearchIndexer.java
  repository/src/main/java/org/apache/atlas/repository/patches/AtlasPatchRegistry.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/DeleteHandlerV1.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/tasks/ClassificationTask.java
  repository/src/main/java/org/apache/atlas/tasks/AbstractTask.java
  repository/src/main/java/org/apache/atlas/tasks/AtlasTaskService.java
  repository/src/main/java/org/apache/atlas/tasks/TaskExecutor.java
  repository/src/main/java/org/apache/atlas/tasks/TaskFactory.java
  repository/src/main/java/org/apache/atlas/tasks/TaskRegistry.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
Labels: READY FOR REVIEW

#3939 FT-891 Incorrect response code given the error for Index search gateway timeout
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchQuery.java
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
Labels: READY FOR REVIEW

#3972 FT-891 Incorrect response code given the error for Index search gateway timeout
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchQuery.java
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
Labels: READY FOR REVIEW

#3967 DG-1986 | Use policy update time as last refresh time
  auth-agents-common/src/main/java/org/apache/atlas/plugin/service/RangerBasePlugin.java
  auth-agents-common/src/main/java/org/apache/atlas/plugin/util/PolicyRefresher.java
  auth-agents-common/src/main/java/org/apache/atlas/policytransformer/CachePolicyTransformerImpl.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  webapp/src/main/java/org/apache/atlas/web/rest/AuthREST.java
Labels: READY FOR REVIEW

#4031 MLH-36 | Migrate index : ranger audits
  atlas-hub/pre-conf/atlas-auth/atlas-atlas-audit.xml
  pom.xml
Labels: master

#4051 MLH-80 : (feat) Add flag to disable edge restoration during entity restoration
  graphdb/api/src/main/java/org/apache/atlas/repository/graphdb/AtlasVertex.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusVertex.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/RestoreHandlerV1.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: READY FOR REVIEW

#4052 MLH-36 | remove all log4j dependencies
  addons/falcon-bridge/pom.xml
  addons/hbase-testing-util/pom.xml
  addons/hdfs-model/pom.xml
  addons/hive-bridge/pom.xml
  addons/impala-bridge/pom.xml
  addons/sqoop-bridge/pom.xml
  notification/pom.xml
  pom.xml
  test-tools/pom.xml
  tools/classification-updater/pom.xml
  webapp/pom.xml
Labels: bug, READY FOR REVIEW, master
