Repository atlanhq/atlas-metastore, pull requests merged in 2025-03, with the labels that each got.

#3908 PLT-2979 : (feat)add request isolation from client level in indexsearch
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchDatabase.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchQuery.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusGraph.java
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasJanusGraphDatabase.java
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
Labels: READY FOR REVIEW

#4339 MLH-173 Quick Fix to relieve WF runs on exelixis
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
Labels: DO NOT MERGE

#4352 MLH-73 | Cassandra optimisation. Optimise edgeLabel fetching only to root level vertices
  .github/workflows/maven.yml
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: READY FOR REVIEW

#4013 MESH-365 : Execution API for Business Lineage
  common/src/main/java/org/apache/atlas/repository/Constants.java
  intg/src/main/java/org/apache/atlas/model/instance/BusinessLineageRequest.java
  repository/src/main/java/org/apache/atlas/repository/businesslineage/AtlasBusinessLineageService.java
  repository/src/main/java/org/apache/atlas/repository/businesslineage/BusinessLineageService.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/AtlasRelationshipStore.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasRelationshipStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  webapp/src/main/java/org/apache/atlas/web/rest/BusinessLineageREST.java
Labels: READY FOR REVIEW

#4159 MESH-363 : Additional info for outptuPort update event
  common/src/main/java/org/apache/atlas/repository/Constants.java
  intg/src/main/java/org/apache/atlas/model/instance/AtlasEntity.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
  webapp/src/main/java/org/apache/atlas/notification/EntityNotificationListenerV2.java
Labels: READY FOR REVIEW

#4472 MLH-213 | Reuse cassandra optimization across indexsearch
  .github/workflows/maven.yml
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: READY FOR REVIEW, master, java

#4517 Sync Java 17 canary to latest master
  .github/workflows/maven.yml
  addons/static/templates/policy_cache_transformer_persona.json
  common/src/main/java/org/apache/atlas/repository/Constants.java
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/aliasstore/ESAliasStore.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/DeleteHandlerV1.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/AuthPolicyValidator.java
  repository/src/main/java/org/apache/atlas/repository/util/AccessControlUtils.java
Labels: DO NOT MERGE

#4532 APP-5891 Gateway Timeout check for ES
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchQuery.java
Labels: READY FOR REVIEW

#4533 APP-5891 Gateway Timeout check for ES
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchQuery.java
Labels: READY FOR REVIEW
