Repository atlanhq/atlas-metastore, pull requests merged in 2025-02, with the labels that each got.

#4151 Beta | Janus upgrade
  .gitignore
  auth-audits/pom.xml
  common/src/main/java/org/apache/atlas/service/redis/AbstractRedisService.java
  graphdb/janus/pom.xml
  repository/pom.xml
  repository/src/main/java/org/apache/atlas/repository/graph/IndexRecoveryService.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
Labels: beta

#4157 MLH-107 : (feat) Add metrics for the bulk entity creation for more observability
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/DeleteHandlerV1.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
Labels: READY FOR REVIEW

#4163 Delete params
  repository/src/main/java/org/apache/atlas/repository/store/graph/v1/DeleteHandlerV1.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
  webapp/src/main/java/org/apache/atlas/web/filters/AuditFilter.java
  webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: beta, java

#4185 Bulk limit
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  repository/src/main/java/org/apache/atlas/repository/audit/ESBasedAuditRepository.java
  repository/src/main/java/org/apache/atlas/repository/audit/EntityAuditListenerV2.java
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: java, staging

#4223 MLH-153 | Hard limit entities
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: READY FOR REVIEW, master

#4242 MLH-153 | add metrics to get number of throttled request
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: READY FOR REVIEW, master

#4186 Improve bulk API call Tag mutations
  intg/src/main/java/org/apache/atlas/model/instance/AtlasEntity.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/AtlasEntityStore.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityComparator.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/BulkRequestContext.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/ClassificationAssociator.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/contract/ContractPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/util/AtlasEntityUtils.java
  repository/src/main/java/org/apache/atlas/repository/util/AtlasEntityUtilsTest.java
  repository/src/main/java/org/apache/atlas/repository/util/AtlasEntityUtilsTestAppend.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: DO NOT MERGE

#4213 MLH-139 : (feat) add distributed tasks in metastore to cleanup unused relationships
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/model/notification/AtlasDistributedTaskNotification.java
  notification/src/main/java/org/apache/atlas/kafka/KafkaNotification.java
  notification/src/main/java/org/apache/atlas/notification/NotificationInterface.java
  notification/src/main/java/org/apache/atlas/notification/task/AtlasDistributedTaskMessageDeserializer.java
  notification/src/main/java/org/apache/atlas/notification/task/AtlasDistributedTaskNotificationSender.java
  repository/pom.xml
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityNotifierImpl.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/bulkimport/MigrationImport.java
Labels: READY FOR REVIEW

#4260 MLH-169 | Optimise janus query
  common/src/main/java/org/apache/atlas/repository/Constants.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: READY FOR REVIEW, master, java

#4288 MLH-170 | Skip prefetching for S3Bucket
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: master
