Repository atlanhq/atlas-metastore, pull requests merged in 2025-06, with the labels that each got.

#4836 APP-6770 | Change error code for type lock to 423 rather than 500
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
Labels: READY FOR REVIEW

#4843 MLH-512 : (feat) add logic to set hasLineage correctly for append and remove relation flow
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
Labels: READY FOR REVIEW

#4831 PLTS-334 | Include deny policies in persona alias query
  repository/src/main/java/org/apache/atlas/repository/store/aliasstore/ESAliasStore.java
Labels: DO NOT MERGE

#4762 MESH-407 | Hard Deletion of Assets and Products
  repository/src/main/java/org/apache/atlas/discovery/EntityDiscoveryService.java
  repository/src/main/java/org/apache/atlas/repository/businesslineage/BusinessLineageService.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/AssetPreProcessor.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/preprocessor/PreProcessorUtils.java
Labels: READY FOR REVIEW

#4892 MLH-662 CM update API taking longer
  repository/src/main/java/org/apache/atlas/repository/converters/AtlasInstanceConverter.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityChangeNotifier.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
Labels: DO NOT MERGE, READY FOR REVIEW
