Repository atlanhq/atlas-metastore, pull requests merged in 2025-08, with the labels that each got.

#5041 MLH-892 Fix repairClassificationsMappings API for V2 and support for bulk repair
  repository/src/main/java/org/apache/atlas/repository/store/graph/AtlasEntityStore.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/AtlasEntityStoreV2.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphMapper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityMutationService.java
  repository/src/main/java/org/apache/atlas/repository/util/TagDeNormAttributesUtil.java
  webapp/src/main/java/org/apache/atlas/web/rest/EntityREST.java
Labels: DO NOT MERGE

#5036 MLH-891 Fix redundant refresh propagation tasks creation
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
Labels: READY FOR REVIEW

#5038 MLH-894 | Restrict the number of relationships in indexsearch via product
  .github/workflows/maven.yml
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchQuery.java
  intg/src/main/java/org/apache/atlas/AtlasConfiguration.java
  intg/src/main/java/org/apache/atlas/AtlasErrorCode.java
  repository/src/main/java/org/apache/atlas/discovery/AtlasDiscoveryService.java
  repository/src/main/java/org/apache/atlas/discovery/EntityDiscoveryService.java
  repository/src/main/java/org/apache/atlas/repository/EdgeVertexReference.java
  repository/src/main/java/org/apache/atlas/repository/VertexEdgePropertiesCache.java
  repository/src/main/java/org/apache/atlas/repository/graph/GraphHelper.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/EntityGraphRetriever.java
  repository/src/main/java/org/apache/atlas/repository/util/AccessControlUtils.java
  repository/src/main/java/org/apache/atlas/tasks/AtlasTaskService.java
  server-api/src/main/java/org/apache/atlas/RequestContext.java
  webapp/src/main/java/org/apache/atlas/web/filters/AtlasResponseRequestWrapper.java
  webapp/src/main/java/org/apache/atlas/web/filters/AuditFilter.java
  webapp/src/main/java/org/apache/atlas/web/rest/DiscoveryREST.java
Labels: master

#5047 MLH-755 DSL optimiser with validation
  .github/workflows/maven.yml
  graphdb/janus/src/main/java/org/apache/atlas/repository/graphdb/janus/AtlasElasticsearchQuery.java
  intg/src/main/java/org/apache/atlas/model/discovery/IndexSearchParams.java
  repository/src/main/java/org/apache/atlas/discovery/ElasticsearchDslOptimizer.java
  repository/src/main/java/org/apache/atlas/discovery/EntityDiscoveryService.java
  repository/src/test/java/org/apache/atlas/discovery/ElasticsearchDslOptimizerTest.java
  repository/src/test/resources/fixtures/dsl_rewrite/aggregation_complex.json
  repository/src/test/resources/fixtures/dsl_rewrite/aggs_filter.json
  repository/src/test/resources/fixtures/dsl_rewrite/bool_single_should_flatten.json
  repository/src/test/resources/fixtures/dsl_rewrite/database_entity_filter.json
  repository/src/test/resources/fixtures/dsl_rewrite/dq_rule_template.json
  repository/src/test/resources/fixtures/dsl_rewrite/entity_types_array.json
  repository/src/test/resources/fixtures/dsl_rewrite/entity_types_bool_mix.json
  repository/src/test/resources/fixtures/dsl_rewrite/entity_types_multi.json
  repository/src/test/resources/fixtures/dsl_rewrite/entity_types_nested.json
  repository/src/test/resources/fixtures/dsl_rewrite/entity_types_simple.json
  repository/src/test/resources/fixtures/dsl_rewrite/func_score_advanced.json
  repository/src/test/resources/fixtures/dsl_rewrite/func_score_basic.json
  repository/src/test/resources/fixtures/dsl_rewrite/func_score_bool_flatten.json
  repository/src/test/resources/fixtures/dsl_rewrite/func_score_bool_nested.json
  repository/src/test/resources/fixtures/dsl_rewrite/func_score_column_terms.json
  repository/src/test/resources/fixtures/dsl_rewrite/func_score_filter_opt.json
  repository/src/test/resources/fixtures/dsl_rewrite/func_score_multi_clause.json
  repository/src/test/resources/fixtures/dsl_rewrite/func_score_qualified_name.json
  repository/src/test/resources/fixtures/dsl_rewrite/func_score_regexp_search.json
  repository/src/test/resources/fixtures/dsl_rewrite/link_entity_filter.json
  repository/src/test/resources/fixtures/dsl_rewrite/must_not_wildcards.json
  repository/src/test/resources/fixtures/dsl_rewrite/purpose_double_bool.json
  repository/src/test/resources/fixtures/dsl_rewrite/range_query_optimization.json
  repository/src/test/resources/fixtures/dsl_rewrite/schema_entity_filter.json
  repository/src/test/resources/fixtures/dsl_rewrite/tag_attachment_filter.json
  repository/src/test/resources/fixtures/dsl_rewrite/task_bool_simple.json
  repository/src/test/resources/fixtures/dsl_rewrite/task_filter_context.json
  repository/src/test/resources/fixtures/dsl_rewrite/task_nested_bool_complex.json
  repository/src/test/resources/fixtures/dsl_rewrite/task_terms_consolidate.json
  repository/src/test/resources/fixtures/dsl_rewrite/wildcard_performance_test.json
  repository/src/test/resources/fixtures/dsl_rewrite/wildcard_staging.json
  repository/src/test/resources/fixtures/dsl_rewrite/wildcards_too_many.json
Labels: READY FOR REVIEW

#5285 MLH-1075 | Auto repair corrrupted vertices
  .github/workflows/maven.yml
  intg/src/main/java/org/apache/atlas/model/repair/BatchRepairRequest.java
  intg/src/main/java/org/apache/atlas/model/repair/BatchRepairResult.java
  intg/src/main/java/org/apache/atlas/model/repair/RepairEntry.java
  intg/src/main/java/org/apache/atlas/model/repair/RepairRequest.java
  intg/src/main/java/org/apache/atlas/model/repair/RepairResult.java
  repository/src/main/java/org/apache/atlas/repository/store/graph/v2/IndexRepairService.java
  webapp/src/main/java/org/apache/atlas/web/rest/RepairREST.java
Labels: master
